import type { ProjectData } from "@/components/widgets/types";

export const PROJECTS: ProjectData[] = [
  {
    id: "outcomes-tracker",
    slug: "outcomes-tracker",
    title: "Outcomes Tracker",
    description:
      "Tracking progress of key government commitments and their impact",
    externalUrl: "/tracker",
    size: "small",
    featured: true,
    order: 0,
    accentColor: null,
    imageUrl: "/projects/outcomes-tracker.png",
  },
  {
    id: "canada-spends",
    slug: "canada-spends",
    title: "Canada Spends",
    description:
      "Breaking down government finances to understand how your money is being spent",
    externalUrl: "https://canadaspends.com",
    size: "small",
    featured: false,
    order: 1,
    accentColor: null,
    imageUrl: "/projects/canada-spends.png",
  },
  {
    id: "builder-mp",
    slug: "builder-mp",
    title: "Builder MP",
    description: "What would a Builder think of these parliament bills?",
    externalUrl: "https://buildcanada.com/bills",
    size: "small",
    featured: false,
    order: 2,
    accentColor: null,
    imageUrl: "/projects/builder-mp.png",
  },
  {
    id: "great-canadian-builders",
    slug: "great-canadian-builders",
    title: "Great Canadian Builders",
    description: "Stories of Canadians who have transformed our world",
    externalUrl: "/great-canadian-builders",
    size: "small",
    featured: false,
    order: 3,
    accentColor: null,
    imageUrl: "/projects/great-canadian-builders.png",
  },
  {
    id: "state-of-the-nation",
    slug: "state-of-the-nation",
    title: "State of the Nation",
    description: "Visualize and track key indicators in Canada.",
    externalUrl: "/state-of-the-nation",
    size: "small",
    featured: false,
    order: 4,
    accentColor: null,
    imageUrl: "/projects/state-of-the-nation.png",
  },
  {
    id: "trade-barriers-tracker",
    slug: "trade-barriers-tracker",
    title: "Trade Barriers Tracker",
    description:
      "Tracking progress of interprovincial trade agreements across Canada",
    externalUrl: "https://buildcanada.com/trade-barriers",
    size: "small",
    featured: false,
    order: 5,
    accentColor: null,
    imageUrl: "/projects/trade-barriers-tracker.png",
  },
  {
    id: "tax-visualizer",
    slug: "tax-visualizer",
    title: "Where Your Tax Dollars Go",
    description:
      "A personalized breakdown of how much you contribute to different government services",
    externalUrl: "https://canadaspends.com/tax-visualizer",
    size: "small",
    featured: false,
    order: 6,
    accentColor: null,
    imageUrl: "/projects/tax-visualizer.png",
  },
  {
    id: "exit-tax-calculator",
    slug: "exit-tax-calculator",
    title: "Exit Tax Calculator",
    description:
      "Compare exit scenarios for founders and investors in Canada vs. US",
    externalUrl: "https://buildcanada.com/exit-tax-calculator",
    size: "small",
    featured: false,
    order: 7,
    accentColor: null,
    imageUrl: "/projects/exit-tax-calculator.png",
  },
];
