import type { Metadata } from "next";
import PollInformationPage from "../PollInformationPage";

export const metadata: Metadata = {
  title: { absolute: "Build Canada Polling - Privacy Policy" },
  description: "How Build Canada Polling collects, uses, and protects personal information in public-opinion surveys.",
  alternates: { canonical: "/polls/privacy-policy" },
};

export default function PollPrivacyPolicyPage() {
  return <PollInformationPage title="Build Canada Polling - Privacy Policy">{`
## 1. Who we are

Build Canada ("we", "us") conducts public-opinion surveys of Canadian adults. This policy covers personal information handled in that research. It is separate from, and additional to, the [general Build Canada privacy notice](/privacy-notice). Privacy contact: [polling@buildcanada.com](mailto:polling@buildcanada.com).

## 2. What we collect and why

- **Telephone numbers.** Generated by random digit dialing methods or screened through line-type lookup services; used solely to send survey invitations and honour opt-outs. We do not buy contact lists.
- **Survey responses.** Opinions and demographic information (such as age range, gender, education, and area of residence) you choose to provide.
- **Technical data.** Message delivery status, response timestamps, browser/device type, and a device identifier used only to prevent duplicate responses.
- **Messaging opt-in data and consent records.** Your messaging preferences and records of consent or withdrawal; used to manage optional follow-up messages and honour opt-out requests.

We use this information for one purpose: producing statistical research. Results are published only in aggregate. We do not use survey data for marketing, we do not sell or rent personal information, and our invitations contain no commercial content.

## 3. Consent

Receiving an invitation does not obligate you to anything. Consent is given by choosing to answer, question by question; declining or stopping at any point is honoured immediately and partial answers may be excluded on request. Reply STOP (or ARRET) to any message to be placed on a permanent do-not-contact list. Persons under 18 are screened out and their responses discarded.

**Optional follow-up.** If you opt in at the end of a survey, we may contact you with the survey's results or for prize awards. This contact is entirely optional, and can be withdrawn at any time by replying STOP.

## 4. Disclosure

Published datasets and tables never contain telephone numbers, device identifiers, or any combination of fields that could identify an individual. Identifiable information is disclosed to no one, except service providers processing data on our instructions (telecommunications and hosting providers) under contractual confidentiality, or where the law requires.

Messaging opt-in data and consent will not be shared with third parties.

## 5. Retention and de-identification

Telephone numbers are separated from survey responses when fieldwork closes. The linkage needed for quality control is destroyed after [90] days, after which retained research data is de-identified. Phone numbers and or email addresses are only kept on an opt-in basis. Suppression-list numbers are kept indefinitely, solely to honour opt-outs. Backups age out on a fixed schedule.

## 6. Safeguards

Personal information is encrypted in transit and at rest, access is limited to research staff who need it. Service providers may process data outside Canada; where they do, it remains subject to contractual protections, and we will identify processing jurisdictions on request.

## 7. Your rights

You may ask what personal information we hold about you, request correction, withdraw consent, or ask that your responses be deleted (possible until responses are de-identified, after which they can no longer be linked to you). Write to [polling@buildcanada.com](mailto:polling@buildcanada.com). We respond within 30 days.

## 8. Verification

Our fieldwork is registered with the CRIC Research Verification Service, where you can confirm that a survey invitation from us is genuine and lodge feedback.

## 9. Changes

Material changes to this policy will be posted at this address with a revision date. Effective date: 2026-09-11.
`}</PollInformationPage>;
}
